### PR TITLE
Reset materials when applying designs

### PR DESCRIPTION
**Pull request by anya-hichu**
Objective: Reproducible design results

Prevents previously updated advanced dyes (manual UI update or design application) from impacting new design applications.

### CODE REVIEW

**Comment by Ottermandias** [comment]
Why would you think this is desired? This is not how design application behaves for any other thing where it does not apply things.
This would make a "hair style change only"-design reset all your materials when applied.

**Comment by anya-hichu** [comment]
1) If I apply "Design A" that has an "Advanced Dye" on "Mat A Row 8B" with Diffuse "Pink" for the body
2) Then I apply "Design B" that doesn't define advanced dyes
=> It will result in a Pink body with "Design B" instead of the default value because the state is persisted

**Comment by Ottermandias** [comment]
Yes, just like any other design applies whatever it applies on top.

**Comment by Ottermandias** [comment]
You can add revert rows to the designs. There might be some other mechanism that could make the experience better. But what you've PR'd just breaks any layered design application.
If you have a design that only applies a hairstyle or wetness or whatever, and apply this, this would remove all advanced dyes from any prior design applications. And that's certainly not intended.

**Pull request closed without merging**
